name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Backend to Render
        run: |
          curl -X POST ${{ secrets.RENDER_BACKEND_DEPLOY_HOOK }}

      - name: Deploy Frontend to Render
        run: |
          curl -X POST ${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK }}
